# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUol():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uol(self):
    self.driver.get("https://www.uo.com.br/")
    self.driver.set_window_size(1054, 808)
    element = self.driver.find_element(By.CSS_SELECTOR, ".HU_canal__esporte .HU_menu__title")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".show > .HU_menu__title").click()
    self.driver.execute_script("window.scrollTo(0,616)")
    self.driver.execute_script("window.scrollTo(0,1135.199951171875)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(1) > .thumbnail-standard-wrapper .thumb-title")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(1) > .thumbnail-standard-wrapper .thumb-title").click()
  
